In [2]:
from dataset.datasets import VideoClsDataset

/opt/conda/envs/videomae/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
video_path="/tsukimi/datasets/Chiba/cut_videos"
mapping_file="/tsukimi/datasets/Chiba/persistence/video_label_map_filtered.json"
folder_map="/tsukimi/datasets/Chiba/persistence/video_folder_map.pkl"
import json
import os
import os.path as op
with open(mapping_file) as f:
    label_map = json.load(f)

import pickle
with open(folder_map, 'rb') as f:
    folder_map = pickle.load(f)
    
path_label_list=[]    
label_set=set()

for video in label_map:
    for eaf in label_map[video]:
        eaf_name=eaf.split('/')[-1]
        for clip in label_map[video][eaf]:
            label=clip[0]
            clip[1]=str(clip[1])
            clip[2]=str(clip[2])
            clip_name='_'.join(clip)+'.mov'
            clip_path=op.join(video_path, video, eaf_name, clip_name)
            path_label=' '.join([clip_path, label])
            path_label_list.append(path_label)
            label_set.add(label)

In [9]:
# map label set to 0~n
label_map={}
for i, label in enumerate(label_set):
    label_map[label]=i
print(label_map)

{'restrainer_interaction': 0, 'unsupported_rearing': 1, 'running': 2, 'immobility': 3, 'idle_actions': 4, 'interaction_with_partner': 5, 'climbing_on_side': 6}


In [20]:
# map label set to 0~n
label_map={}
for i, label in enumerate(label_set):
    label_map[label]=i

for i, path_label in enumerate(path_label_list):
    path, label=path_label.split()
    label=label_map[label]
    path_label_list[i]=' '.join([path, str(label)])

In [25]:
# # save path_label_list to csv file
# import pandas as pd
# df=pd.DataFrame(path_label_list)
# df

# train validation test split
from sklearn.model_selection import train_test_split
train, test=train_test_split(path_label_list, test_size=0.2, random_state=42)
train, val=train_test_split(train, test_size=0.2, random_state=42)

# save to csv
import pandas as pd
df_train=pd.DataFrame(train)
df_val=pd.DataFrame(val)
df_test=pd.DataFrame(test)

save_path="/tsukimi/datasets/Chiba/baseline"
df_train.to_csv(op.join(save_path, 'train.csv'), index=False, header=False)
df_val.to_csv(op.join(save_path, 'val.csv'), index=False, header=False)
df_test.to_csv(op.join(save_path, 'test.csv'), index=False, header=False)

In [27]:
dataset=VideoClsDataset(anno_path=op.join(save_path, 'train.csv'))

AttributeError: 'dict' object has no attribute 'reprob'

In [30]:
import torch
import torch.nn.functional as F

# Example logits and target
x = torch.tensor([[0.1, 2.2, 3.1], [1.0, 2.0, 1.5]])  # logits for 2 samples, 3 classes each
target = torch.tensor([2, 1])  # true class indices

# Compute log_softmax
logprobs = F.log_softmax(x, dim=-1)
print(logprobs)
# Gather the log probabilities of the actual classes
selected_log_probs = logprobs.gather(dim=-1, index=target.unsqueeze(1))

# Resulting tensor of selected log probabilities
selected_log_probs

tensor([[-3.3759, -1.2759, -0.3759],
        [-1.6803, -0.6803, -1.1803]])


tensor([[-0.3759],
        [-0.6803]])

In [13]:
import torch
import torch.nn as nn

# Assuming the following mapping of labels to indices: A -> 0, B -> 1, C -> 2
label_mapping = {'A': 0, 'B': 1, 'C': 2}

# Example raw labels
raw_labels = ['A&B', 'B&C', 'A&C','A&A']

# Function to convert raw labels to one-hot encoded format
def ground_truth_decoder(labels,num_classes=len(label_mapping)):
    decoded = torch.zeros((len(labels), num_classes))
    for i, label in enumerate(labels):
        parts = label.split('&')
        for part in parts:
            decoded[i, label_mapping[part]] += 1
    return decoded/2

# One-hot encoded targets
targets = ground_truth_decoder(raw_labels)
print(targets)
# Example outputs from the model (logits)
outputs = torch.randn(4, 3)  # Batch size of 3, and 3 classes

# Define the loss function
criterion = nn.BCEWithLogitsLoss()

# Calculate loss
loss = criterion(outputs, targets)
print("Loss:", loss.item())


tensor([[0.5000, 0.5000, 0.0000],
        [0.0000, 0.5000, 0.5000],
        [0.5000, 0.0000, 0.5000],
        [1.0000, 0.0000, 0.0000]])
Loss: 0.8683392405509949


In [4]:
from eventutils import multi_label_accuracy,custom_multi_label_pred,ground_truth_decoder
import torch
# Example outputs from the model (logits)
outputs = torch.tensor([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
# Example targets
targets = torch.tensor([[0, 0.5, 0.5], [0.5, 0, 0.5], [0, 0, 1]])
preds=custom_multi_label_pred(outputs)
print(preds)
acc=multi_label_accuracy(outputs, targets)
print(acc)

tensor([[0.0000, 0.5000, 0.5000],
        [0.0000, 0.5000, 0.5000],
        [0.0000, 0.0000, 1.0000]])
tensor(0.8333)
